export const create_practitioner = [
    {
        "label":"Name",
        "type":"text",
        "required":true,
        "name":"practitioner_name"
    },
    {
        "label":"Title",
        "type":"dropdown",
        "required":true,
        "name":"title",
        "options":[
            {
                "label":"MD",
                "value":"MD"
            },
            {
                "label":"NP",
                "value":"NP"
            },
            {
                "label":"PA",
                "value":"PA"
            }
        ]
    },
    {
        "label":"Telehealth Link",
        "type":"text",
        "required":false,
        "name":"telehealth_link"
    }
];